### ISSUE TITLE
SequelizeConnectionError: Unknown or incorrect time zone: '+5.5:00'

### ISSUE THREAD

**Issue by jarod** [TarsCloud/TarsWeb#84]
```bash
mysql> SELECT @@global.time_zone, @@session.time_zone;
+--------------------+---------------------+
| @@global.time_zone | @@session.time_zone |
+--------------------+---------------------+
| +05:30             | +05:30              |
+--------------------+---------------------+
1 row in set (0.01 sec)
```

```bash
SequelizeConnectionError: Unknown or incorrect time zone: '+5.5:00'
    at /usr/local/tars/cpp/deploy/web/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:133:19
    at tryCatcher (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by jarod** [comment]
以前的版本处理过类似的问题 #3
